loc_name = By.XPATH, '//input[@name="username"]'
loc_password = By.XPATH, '//input[@name="password"]'
loc_sign_in = By.XPATH, '//input[@type="submit"]'
loc_Customer = By.XPATH, '//span[@title="客服管理"]'
loc_Order_Management = By.XPATH, '//a[@title="客服订单查询"]'
iframe = By.ID, "main_frame"
search = By.XPATH, '//textarea[@class="form-control"]'
submit_order_sn = By.ID, 'checkStartTime'
order_detail = By.XPATH, '//td/a[@target="_blank"]'
loc_Confirm_Order = By.XPATH, '//a[contains(text(),"Confirm Order")]'
loc_submit_Confirm = By.XPATH, '//td/input[@value="Submit"]'
loc_purchase = By.XPATH, '//span[@title="采购管理"]'
loc_source_ = By.XPATH, '//a[@title="工单管理"]'

loc_Generate_Source_Order = By.XPATH, '//a[@title="未制作的工单"]'
loc_iframe2 = By.ID, 'main_frame'
loc_externalOrderSn = By.XPATH, '//input[@name="row[externalOrderSn]"]'
loc_select_option = By.XPATH, '//select[@name="or_email[]"]'
loc_yes_option = By.XPATH, '//select[@name="confirm_order"]/option[@value="Y"]'
loc_search_gd_button = By.XPATH, '//input[@value="查询待下工单 "]'
loc_create_gd_button = By.XPATH, '//a[contains(text(),"生成工单")]'
loc_create_gd_button2 = By.XPATH, '//input[@value=" 生成工单 "]'
loc_ship_time = By.XPATH, '//input[@id="shippingCalendar" ]'

loc_new_gd = By.XPATH, '//a[@title="未找到工厂的工单（新）"]'
loc_iframe3 = By.ID, 'main_frame'

loc_input_order = By.XPATH, '//input[@id="zzOrderSn"]'
loc_search_gd = By.XPATH, '//input[@value=" 查询工单 "]'
loc_select_operator = By.XPATH, '//select[@id="_provider_id_7968820"]'
loc_a_operator = By.XPATH, '//select[@id="_provider_id_7968820"]/option[text()="aztestaaa"]'
loc_allocation_gd = By.XPATH, '//input[@value="分派选择的工单"]'

loc_Warehouse = By.XPATH, '//span[text()="Warehouse"]'
loc_send_to_OW = By.XPATH, '//a[@title="发往海外"]'
loc_gd_rk = By.XPATH, '//a[contains(text(),"Entry Scan") and @title="工单入库" ]'
loc_multiBox = By.XPATH, '//input[@id="multiBox"]'
loc_singleBox = By.XPATH, '//input[@id="singleBox"]'
loc_gd_sn = By.XPATH, '//input[@id="dispatchListSn"]'
loc_kucun_box = By.XPATH, '//input[@id="kucunBox"]'
loc_submit_gd = By.XPATH, '//button[@id="singleBoxSubmit"]'
loc_ = By.XPATH, ''
loc_ = By.XPATH, ''
loc_ = By.XPATH, ''